import { Box, Container, Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import CallToAction from "../components/CallToAction";
import Carousel from "../components/Carousel";
import FeaturesColumn from "../components/Features";
import Footer from "../components/Footer";
import Nav from "../components/Nav";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Custxmer Text App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Container pt={4} maxW={"5xl"}>
        <CallToAction />

        <Carousel />
      </Container>
      <Box bg={"brand.200"} my={16}>
        <Container py={16} maxW={"7xl"}>
          <FeaturesColumn />
        </Container>
      </Box>
      <Footer />
    </>
  );
};

export default Home;
