import { Box, Container } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import FeaturesColumn from "../components/Features";
import Footer from "../components/Footer";
import Nav from "../components/Nav";

const Service: NextPage = () => {
  return (
    <>
      <Head>
        <title>Service | Custxmer Text App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Box bg={"brand.200"} my={16}>
        <Container py={16} maxW={"7xl"}>
          <FeaturesColumn />
        </Container>
      </Box>
      <Footer />
    </>
  );
};

export default Service;
